package com.makers.makersbnb.controller;

import com.makers.makersbnb.model.Space;
import com.makers.makersbnb.repository.SpaceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.view.RedirectView;

@RestController
public class StaticPageController {
    // Automatically provides the SpaceRepository so we can interact with the spaces table
    @Autowired
    SpaceRepository spaceRepository;

    @GetMapping("/")
    public ModelAndView welcome() {
        ModelAndView modelAndView = new ModelAndView("/LandingPage");

        // Counts the number of spaces currently stored in the database
        Long nSpaces = spaceRepository.count();
        // this next line makes nSpaces available in the template
        modelAndView.addObject("nSpaces", nSpaces);

        // imagine this value was generated by querying the database
        Integer nBookings = 123;
        // this next line makes nBookings available in the template
        modelAndView.addObject("nBookings", nBookings);

        // imagine these reviews were stored in a database
        String[] reviews = new String[] {"Awesome", "Nice", "Perfect"};
        modelAndView.addObject("reviews", reviews);
        return modelAndView;
    }

    @GetMapping("/spaces")
    public ModelAndView spaces() {
        ModelAndView modelAndView = new ModelAndView("/spaces");

        // get all spaces from the database
        Iterable<Space> spaces = spaceRepository.findAll();

        // make them available to spaces.html
        modelAndView.addObject("spaces", spaces);

        return modelAndView;
    }

    @GetMapping("/contactus")
    public ModelAndView contactUs() {
        return new ModelAndView("/contactus");
    }

    @GetMapping("/team")
    public ModelAndView index() {
        return new ModelAndView("/index");
    }

    @GetMapping("/spaces/new")
    public ModelAndView newSpaceForm() {
        // this is the space referred to in th:object (look back at the form code (spaces/New))
        Space space = new Space();
        ModelAndView newSpaceForm = new ModelAndView("spaces/new");
        newSpaceForm.addObject("space", space);
        return newSpaceForm;
    }

    @PostMapping("/spaces")
// Spring Boot uses the form data to create an instance of space
// which is then passed in as an arg here
    public RedirectView create(Space space) {
        spaceRepository.save(space);
        // assumes you already created a method to handle `GET "/spaces"`
        return new RedirectView("/spaces");
    }


}
